apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-http-servicediscovery-confluent-cloud
  labels:
    app: prometheus-http-servicediscovery-confluent-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-http-servicediscovery-confluent-cloud
  template:
    metadata:
      labels:
        app: prometheus-http-servicediscovery-confluent-cloud
    spec:
      containers:
      - name: prometheus-http-servicediscovery-confluent-cloud
        image: prometheus-http-servicediscovery-confluent-cloud:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONFLUENT_API_KEY
          valueFrom:
            secretKeyRef:
              name: confluent-cloud-credentials
              key: api-key
        - name: CONFLUENT_API_SECRET
          valueFrom:
            secretKeyRef:
              name: confluent-cloud-credentials
              key: api-secret
        - name: CACHE_DURATION
          value: "30"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-http-servicediscovery-confluent-cloud
spec:
  selector:
    app: prometheus-http-servicediscovery-confluent-cloud
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: confluent-cloud-credentials
type: Opaque
data:
  # These are placeholders. You should replace them with your actual credentials
  # Use base64 encoded values: echo -n "your-api-key" | base64
  api-key: UkVQTEFDRV9USEVTRV9XSVRIXllPVVJfQVBJX0tFWQ==
  api-secret: UkVQTEFDRV9USEVTRV9XSVRIXllPVVJfQVBJX1NFQ1JFVA==